### ISSUE TITLE
Config is_valid avoids sigmoid

### ISSUE THREAD

**Issue by gatoniel** [CSBDeep/CSBDeep#2]
Hi,

the is_valid function of the Config class, does only check if the **unet_last_activation** is _relu_ or _linear_. I added _sigmoid_ on my own.

But what was the reason, not to add _sigmoid_ there?

**Comment by uschmidt83** [comment]
Hi,

the default image normalization is done (with percentiles) in such a way that the ground truth image can have pixels values below 0 and also above 1. Hence, the output of the network should not be restricted to the range 0...1, which will happen with a *sigmoid* activation function.

Why do you want to use *sigmoid*?

(FYI, the normalization can be changed (see [here](http://csbdeep.bioimagecomputing.com/doc/datagen.html#csbdeep.data.norm_percentiles)) to ensure pixel values >= 0 when *relu* is used for `unet_last_activation`. That's why it is allowed as an option.)

**Comment by gatoniel** [comment]
Hi,

for an explanation why we want to use sigmoid look at #4 .

**Comment by maweigert** [comment]
Closing due to non-activity (please reopen if still relevant)
