### ISSUE TITLE
'RawData' is not defined when loading training data

### ISSUE THREAD

**Issue by Fastander** [CSBDeep/CSBDeep#28]
Very new to python but your example for 2D denoising worked well. When I am trying to proceed with our own data I get this error: name 'RawData' is not defined. What is the way to import it to follow this example and create an npz for training?

data = RawData.from_folder(basepath='data', source_dirs=['source1'], target_dir='GT', axes='CYX')
>>> n_images = data.size
>>> for source_x, target_y, axes, mask in data.generator():

**Comment by uschmidt83** [comment]
I suggest you copy the example notebook that you want to use (e.g. 2D denoising) and then modify it by replacing the data with your own. This should avoid the issue you're having.
If you just want to import `RawData`, you can do this via `from csbdeep.data import RawData`.

Best,
Uwe

**Comment by Fastander** [comment]
Thank you Uwe. My problem is that the example data is in .npz matrix and I don't yet understand how to turn my two folders of GT and source with images with identical names into that .npz format to upload that instead. Do you have an example snipet of how to convert folders into that format that would be legible by CARE?

**Comment by uschmidt83** [comment]
I don't fully understand what your problem exactly is. The `1_datagen.ipynb` notebooks intend to show how correspoding pairs of low- and high-SNR images can be converted to suitable training data. There is also [more documentation about training data generation](http://csbdeep.bioimagecomputing.com/doc/datagen.html).

Best,
Uwe

**Comment by fjug** [comment]
Just in case: you do look at the examples we ship, right? For example this one: https://github.com/CSBDeep/CSBDeep/tree/master/examples/denoising3D

As Uwe said, you might pick the most suitable example, make a copy, and change it so it suits your needs.

More specifically to you question: the ‘1_dataget.ipynb’ file (https://github.com/CSBDeep/CSBDeep/blob/master/examples/denoising3D/1_datagen.ipynb) shows how to create the .npz file from tiff images. 
Under the headline ‘Download example data’, remove the first cell of code, and change the second so it loads the data you are interested in. If it does, great... now you know how to point to the correct data. In order to really go on, you should point to the adequate folders in the next cell. (All is pretty well explained in the example notebook...)

In case you figure out what confused you... please let us know so we can potentially explain matters better.

Best,
Florian

**Comment by Fastander** [comment]
Thank you very much Uwe and Florian! I could not locate the example data loading notebook at http://csbdeep.bioimagecomputing.com/doc so I have only been working with "training" and "prediction". This helps a lot. 
Best,
Alex

**Comment by Fastander** [comment]
My mistake was to start with simple 2D CYX pairs so I didn't go to the 3D example which does contain the datagen notebook...

**Comment by uschmidt83** [comment]
Ok, I understand now. The probabilistic 2D example uses synthetic data and is the only example that doesn't have a dedicated training data generation step. We added this later, mainly to demonstrate how to use a probabilistic model. We should make it clear that it's probably most useful to look at the 3D denoising example first.

Best,
Uwe
