### ISSUE TITLE
Upgrade to TF2.0 or later?

### ISSUE THREAD

**Issue by lacan** [CSBDeep/CSBDeep#30]
Hi all!

Is there a plan to move this repo to TensorFlow 2.0? or to TF 1.14 for example? I am getting a lot of deprecation warnings, as we had it running on a machine with CUDA 10.0 and TF 1.12 won't start with that version.

Not an issue per-se but I would appreciate comments and opinions.

Best

Oli

**Comment by uschmidt83** [comment]
Hi Oli,

TensorFlow 2 has been vaguely on my radar, but I haven't actually looked into it.
TF 1.14 works and is also included in our automatic tests, but there are indeed lots of deprecation warnings (I just installed it myself, but can't fully use it yet on my workstation). However, I've only seen warnings that originate from TF itself and Keras, which I can't do anything about.

There is not much [code that uses TF directly in this repo](https://github.com/CSBDeep/CSBDeep/blob/master/csbdeep/utils/tf.py), hence I hope it won't be too much work to be compatible with newer versions of TF.

Best,
Uwe

**Comment by tboo** [comment]
Hi Oli,

I just updated the [Docker container](https://hub.docker.com/r/tboo/csbdeep_gpu_docker) to CUDA 10 and TF 1.14 if you don't want to or cannot play around with your environment. As Uwe mentioned, CSBDeep runs just fine with TF 1.14.

Best,

Tobias

**Comment by uschmidt83** [comment]
We've just released csbdeep 0.6.0, which does support TensorFlow 2.

**Comment by lacan** [comment]
Awesome! Looking forward!

**Comment by turekg** [comment]
Hi there, I am looking into updating N2V to run with TF2 but csbdeep is still requiring TF1.x. I have indeed verified that the test run with tf2.3.0. However, the setup.py file needs to be updated because tf2.3 requires a newer version of keras (I am using 2.4.3)  Can you please release a new version that updates the setup.py? I could do it myself but I cannot create a branch remotely to issue a pull request

**Comment by turekg** [comment]
Actually, running the tests was not enough. utils/tf.py needs to be updated. I've only discovered this running N2V tests. So I will have to update that code as well

**Comment by uschmidt83** [comment]
Hi @turekg,

> Hi there, I am looking into updating N2V to run with TF2 but csbdeep is still requiring TF1.x.

why do you think that?

> I have indeed verified that the test run with tf2.3.0. However, the setup.py file needs to be updated because tf2.3 requires a newer version of keras (I am using 2.4.3)

The `keras` package is not used at all by `csbdeep` if you use `tensorflow` 2. (You could even uninstall it.)
However, the `csbdeep` package still requires `keras<2.4.0`, because that's needed if you use it with `tensorflow` 1.
I know that's confusing, but we'd otherwise need different requirements depending on the version of `tensorflow`.

The function [`keras_import`](https://github.com/CSBDeep/CSBDeep/blob/c6bd98d9847d4d299cceb151a1b4e18d7599213e/csbdeep/utils/tf.py#L15) automatically imports from the correct package, depending on what's installed. It's a bit clumsy, but allows us to support both TF1 and TF2.

> Can you please release a new version that updates the setup.py? I could do it myself but I cannot create a branch remotely to issue a pull request

It is [recommended](https://github.com/keras-team/keras/releases/tag/2.4.0) to use `tensorflow.keras` going forward. The standalone `keras` package is not developed any further. If you still need it in combination with `tensorflow` 2, you can upgrade it after installing `csbdeep`.

> Actually, running the tests was not enough. utils/tf.py needs to be updated. I've only discovered this running N2V tests. So I will have to update that code as well

If you're referring to [this file](https://github.com/juglab/n2v/blob/master/n2v/utils/tf.py) that imports `CARETensorBoard`, note that this callback has been replaced by [`CARETensorBoardImage`](https://github.com/CSBDeep/CSBDeep/blob/c6bd98d9847d4d299cceb151a1b4e18d7599213e/csbdeep/utils/tf.py#L384) when using TF2. (The API has changed so much that this was necessary.) Unlike `CARETensorBoardImage`, `CARETensorBoardImage` is meant to be used *in addition* to the standard [`tf.keras.callbacks.TensorBoard`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard) callback.

**Comment by turekg** [comment]
Than you Uwe for the explanation. I am going to follow your suggestion and not include a dependency on keras in our setup.py file, letting tf2 provide it. Well see how I get along. Cheers!

**Comment by joaomamede** [comment]
Just to be sure. There's no pip package with 0.6.0 right? It installs 0.5.2 in my case.

If I do the 0.6.0 to use TF2.x would all the csbdeep classes and routines be the same as 0.5.2?

I installed cuda 10.0 libraries to have TF 1.15 and it's running there.

Thanks so much for this! I'll try to restore my ultra-low light viruses live cell imaging with this.

**Comment by uschmidt83** [comment]
> Just to be sure. There's no pip package with 0.6.0 right? It installs 0.5.2 in my case.

I don't know what you mean. There's a PyPI package for csbdeep 0.6.0, see them all [here](https://pypi.org/project/csbdeep/#history).

> If I do the 0.6.0 to use TF2.x would all the csbdeep classes and routines be the same as 0.5.2?

You typically won't notice the difference if you don't use any internals of csbdeep.

> I installed cuda 10.0 libraries to have TF 1.15 and it's running there.

Great! You don't have to use TF 2...

> Thanks so much for this! I'll try to restore my ultra-low light viruses live cell imaging with this.

Good luck,
Uwe

**Comment by joaomamede** [comment]
A new conda env installed the 0.6.1 version.
I got it to run in TF2.0 during the day today.
The only thing that wasn't compatible was the mem fractioning feature, but it's easy to change the csbdeep code to resolve that issue.
