### ISSUE TITLE
maximal value at 3.3e+21

### ISSUE THREAD

**Issue by gatoniel** [CSBDeep/CSBDeep#5]
Hi,

I try to create patches for my own data with your create_patches function. I allready made patches from our big pictures and saved them as .tif with uint16 format. That´s why I only get one patch per image in the code:
```
raw_data = RawData.from_folder (
    basepath    = '/workspace/validation-uint16',
    source_dirs = ['noise_500'],
    target_dir  = 'Boost',
    axes        = 'ZYX',
)

X, Y, XY_axes = create_patches (
    raw_data            = raw_data,
    patch_size          = (32,64,64),
    n_patches_per_image = 1,
    save_file           = '/workspace/csbdeep-validation-uint16-19-6-2018.npz',
    patch_filter        = None,
)
print(np.max(X))
print(np.max(Y))
print(np.argmax(Y))

print(np.min(X))
print(np.min(Y))
```

The output gives:

```
================================================================
 1652 raw images x    1 transformations   =  1652 images
 1652 images     x    1 patches per image =  1652 patches in total
================================================================
Input data:
/workspace/validation-uint16: target='Boost', sources=['noise_500'], axes='ZYX', pattern='*.tif*'
================================================================
Transformations:
1 x Identity
================================================================
Patch size:
32 x 64 x 64
================================================================

100%|| 1652/1652 [00:26<00:00, 62.61it/s]

Saving data to /workspace/csbdeep-validation-uint16-19-6-2018.npz.
3.40611
3.3e+21
175206397
-0.709677
-0.0165891
```

That means there is a huge value in one of the patches. When I train the network I get huge values for the metric very soon. I think those huge metric values come from these huge values in the patches. I thought the value might come from the normalization, but I disabled the normalization and still get this huge value.

Can you tell me, what your functions do, that might cause this huge value?

**Comment by uschmidt83** [comment]
Hi.

> I allready made patches from our big pictures and saved them as .tif with uint16 format. That´s why I only get one patch per image in the code:

Do you want to apply the trained network later on patches of (roughly) this size, or on entire big images? In the latter case, you should also supply them in this size to the `create_patches` function, because the normalization can change depending on whether you use a smaller patch or a large image.

As a general rule of thumb, the training data should in all aspects be as similar as possible to the data that the trained network will be used for.

> That means there is a huge value in one of the patches.

Have you checked your raw data? Does it already contain large values?
(`X` seems to be fine, only `Y` has such large value(s).)

> When I train the network I get huge values for the metric very soon. I think those huge metric values come from these huge values in the patches.

I would think so too.

> I thought the value might come from the normalization, but I disabled the normalization and still get this huge value.

If so, that seems to indicate that the raw data already contains these huge values.
To debug this, you can try setting the minimal value to 0 and the maximal value to 1:

```python
from csbdeep.data import norm_percentiles
create_patches(..., normalization=norm_percentiles(0,100))
```

**Comment by Le-Xiao** [comment]
I've gotten the same issue as yours. Have you solved it? Searching for help!

**Comment by maweigert** [comment]
Closing due to non-activity (please reopen if still relevant)
